export { SITE_URL } from "./seo"

export const APP_URL = "https://nextapp.naura.io"
export const MEETS_URL = "https://meets.naura.io"
export const MEETS_BOT_URL = "https://t.me/CoffeeMeetBot?start=join_global"
export const TELEGRAM_BOT_URL = "https://t.me/nauraio_bot"
export const TELEGRAM_CONTACT_URL = "https://t.me/naura_sp"
export const TELEGRAM_BLOG_URL = "https://t.me/network_aura"
export const BLOG_URL = "https://blog.naura.io"
export const PODCAST_URL = "https://wrongdoor.mave.digital/ep-4"
export const SUPPORT_EMAIL = "naura.io@naura.io"
